<html>
<head>
    <title><?php echo $view->title; ?></title>

    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="./css/metro.css" rel="stylesheet"/>
    <link href="./css/metro-schemes.css" rel="stylesheet"/>
    <link href="./css/metro-responsive.css" rel="stylesheet"/>
    <link href="./css/metro-icons.css" rel="stylesheet"/>

    <link href="./css/style.css" rel="stylesheet"/>
</head>

<body>