<?php require_once("header.phtml"); ?>

<?php require_once("navbar.phtml"); ?>


<div class="padding20" style="width:80%; margin:0 auto;">
    <div class="grid">
        <div class="row cells6">
            <div class="cell">
                test
            </div>
            <div class="cell colspan4">
                <div class="grid">
                    <div class="row">
                        <div class="cell">
                            <form method="post" action="index.php">
                                <div class="row cells10">
                                    <div class="cell colspan9 ">
                                        <div class="input-control text full-size">
                                            <input name="message" type="text">
                                        </div>
                                    </div>
                                    <div class="cell"><input type="submit"></div>
                                </div>
                            </form>
                        </div>
                    </div>

                    <div class="row">
                        tweet
                    </div>
                </div>
            </div>
            <div class="cell">
                test
            </div>
        </div>
    </div>
</div>

<?php require_once("footer.phtml")?>