<div class="app-bar bg-white fg-gray">
    <div style="width:80%; margin:0 auto;">
        <ul class="app-bar-menu place-left ">
            <li><a href="" class="bg-hover-white fg-hover-blue bottom"><span class="mif-home"></span>&nbsp;Home</a></li>
            <li><a href="" class="bg-hover-white fg-hover-blue bottom"><span class="mif-thermometer2"></span>&nbsp;Moments</a></li>
            <li><a href="" class="bg-hover-white fg-hover-blue bottom"><span class="mif-bell"></span>&nbsp;Notifications</a></li>
            <li><a href="" class="bg-hover-white fg-hover-blue bottom"><span class="mif-mail"></span>&nbsp;Messages</a></li>
        </ul>

        <ul class="app-bar-menu place-right ">
            <li><a href="" class="bg-hover-white fg-hover-blue bottom">Search</a></li>
            <li><a href="" class="bg-hover-white fg-hover-blue bottom">Avatar</a></li>
            <li><a href="" class="button primary fg-white"><span class="mif-checkmark "></span>Tweet</a></li>
        </ul>
    </div>
</div>
