<?php require_once("header.phtml"); ?>


<div class="padding20" style="width:80%; margin:0 auto;">
    <div class="grid">
        <div class="row cells6">
            <div class="cell colspan3">
                <h1>Join twitter Now</h1>
                <form method="post" action="index.php">
                    <label>Username</label>
                    <div class="input-control text full-size">
                        <input name="username" type="text">
                    </div>

                    <label>Password</label>
                    <div class="input-control password full-size">
                        <input name="password" type="password">
                    </div>

                    <label>Email</label>
                    <div class="input-control text full-size">
                        <input name="email" type="text">
                    </div>

                    <input type="submit" class="button success">
                </form>
            </div>
            <div class="cell colspan3">Login</div>
        </div>
    </div>
</div>
